// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var source, template;
    source = $("#entry-template").html();
    template = Handlebars.compile(source);
    return $.getJSON("main.json", function(data) {
      return $("body").html(template(data));
    });
  });

}).call(this);
